# -*- coding: utf-8 -*-
"""pfa2: architecture simple CNN+LSTM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4ArlRTa2fWYSaPFErDiaZFl7qPsv0gk

**Test** **imports**
"""

# Test imports
print("Testing imports...")

import os
import ast
import io
import torch
import torch.nn as nn
import torchvision.transforms as transforms
import torchvision.models as models
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import matplotlib.pyplot as plt
import nltk
from nltk.tokenize import word_tokenize
from collections import Counter
import pandas as pd

print("✓ All imports successful")

# Download NLTK data
nltk.download('punkt')
nltk.download('punkt_tab')
print("✓ NLTK data downloaded")

# Check device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"✓ Using device: {device}")
if torch.cuda.is_available():
    print(f"  GPU: {torch.cuda.get_device_name(0)}")
    print(f"  Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

"""**Loading Dataset**"""

# Load the dataset from Kaggle
print("\n" + "="*50)
print("PART 2: Loading Dataset")
print("="*50)

import kagglehub

dataset_path = kagglehub.dataset_download(
    "thedevastator/rsicd-image-caption-dataset"
)

print(f"✓ Dataset path: {dataset_path}")
print(f"✓ Contents: {os.listdir(dataset_path)}")

# Load CSV files
train_df = pd.read_csv(os.path.join(dataset_path, "train.csv"))
valid_df = pd.read_csv(os.path.join(dataset_path, "valid.csv"))
test_df = pd.read_csv(os.path.join(dataset_path, "test.csv"))

print(f"\n✓ Dataset sizes:")
print(f"  Train: {len(train_df)} samples")
print(f"  Valid: {len(valid_df)} samples")
print(f"  Test:  {len(test_df)} samples")

print(f"\n✓ Columns: {train_df.columns.tolist()}")
print(f"\n✓ First row sample:")
print(f"  Filename: {train_df.iloc[0]['filename']}")
print(f"  Captions type: {type(train_df.iloc[0]['captions'])}")
print(f"  Image type: {type(train_df.iloc[0]['image'])}")

"""**Testing Image & Caption Extraction**"""

print("\n" + "="*50)
print("PART 3: Testing Image & Caption Extraction")
print("="*50)

# Helper functions
def extract_image(image_dict_str):
    """Extract PIL Image from the image column"""
    image_dict = ast.literal_eval(image_dict_str)
    image_bytes = image_dict['bytes']
    return Image.open(io.BytesIO(image_bytes)).convert("RGB")

def parse_captions(captions_str):
    """Parse the captions string into a list"""
    return ast.literal_eval(captions_str)

# Test on first image
print("\nTesting with first training image...")
first_row = train_df.iloc[0]

# Extract image
image = extract_image(first_row['image'])
print(f"✓ Image extracted successfully")
print(f"  Size: {image.size}")
print(f"  Mode: {image.mode}")

# Extract captions
captions = parse_captions(first_row['captions'])
print(f"\n✓ Captions extracted: {len(captions)} captions")
for i, caption in enumerate(captions[:3], 1):
    print(f"  {i}. {caption}")

# Display image
plt.figure(figsize=(6, 6))
plt.imshow(image)
plt.axis('off')
plt.title(f"Sample: {first_row['filename']}")
plt.show()

print("\n✓ Image extraction test passed!")

"""**Building Vocabulary**"""

print("\n" + "="*50)
print("PART 4: Building Vocabulary")
print("="*50)

def build_vocab(df_list, min_freq=3):
    """Build vocabulary from dataframes"""
    counter = Counter()
    total_captions = 0

    for df in df_list:
        for idx, row in df.iterrows():
            captions = parse_captions(row['captions'])
            for caption in captions:
                tokens = word_tokenize(caption.lower())
                counter.update(tokens)
                total_captions += 1

    print(f"✓ Processed {total_captions} captions")
    print(f"✓ Found {len(counter)} unique tokens")

    vocab = {"<PAD>": 0, "<START>": 1, "<END>": 2, "<UNK>": 3}
    idx = 4
    for word, freq in counter.items():
        if freq >= min_freq:
            vocab[word] = idx
            idx += 1

    return vocab, counter

# Build vocabulary from train + valid
vocab, word_counter = build_vocab([train_df, valid_df], min_freq=3)
inv_vocab = {v: k for k, v in vocab.items()}
vocab_size = len(vocab)

print(f"\n✓ Vocabulary built:")
print(f"  Vocab size: {vocab_size}")
print(f"  Special tokens: <PAD>, <START>, <END>, <UNK>")

# Show most common words
print(f"\n✓ Top 10 most common words:")
for word, freq in word_counter.most_common(10):
    if word in vocab:
        print(f"  '{word}': {freq} times (index {vocab[word]})")

# Test encoding a caption
test_caption = "Many aircraft are parked at the airport."
tokens = word_tokenize(test_caption.lower())
print(f"\n✓ Testing caption encoding:")
print(f"  Original: {test_caption}")
print(f"  Tokens: {tokens}")
encoded = [vocab["<START>"]] + [vocab.get(t, vocab["<UNK>"]) for t in tokens] + [vocab["<END>"]]
print(f"  Encoded: {encoded}")
decoded = [inv_vocab[i] for i in encoded]
print(f"  Decoded: {decoded}")

"""**Testing Image Transforms**"""

print("\n" + "="*50)
print("PART 5: Testing Image Transforms")
print("="*50)

# Define transforms
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

print("✓ Transform pipeline created:")
print(transform)

# Test transform on an image
test_image = extract_image(train_df.iloc[0]['image'])
print(f"\n✓ Original image size: {test_image.size}")

transformed = transform(test_image)
print(f"✓ Transformed tensor shape: {transformed.shape}")
print(f"✓ Tensor dtype: {transformed.dtype}")
print(f"✓ Value range: [{transformed.min():.2f}, {transformed.max():.2f}]")

# Visualize before and after
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Original
axes[0].imshow(test_image)
axes[0].set_title("Original Image")
axes[0].axis('off')

# Transformed (denormalize for display)
denorm = transformed.permute(1, 2, 0).cpu().numpy()
denorm = denorm * [0.229, 0.224, 0.225] + [0.485, 0.456, 0.406]
denorm = denorm.clip(0, 1)
axes[1].imshow(denorm)
axes[1].set_title("Transformed (224x224, normalized)")
axes[1].axis('off')

plt.tight_layout()
plt.show()

print("\n✓ Transform test passed!")

"""**Testing Dataset Class**"""

print("\n" + "="*50)
print("PART 6: Testing Dataset Class")
print("="*50)

class RSICDDataset(Dataset):
    def __init__(self, df, vocab, transform):
        self.df = df
        self.vocab = vocab
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def encode_caption(self, caption):
        tokens = word_tokenize(caption.lower())
        encoded = [self.vocab["<START>"]]
        for token in tokens:
            encoded.append(self.vocab.get(token, self.vocab["<UNK>"]))
        encoded.append(self.vocab["<END>"])
        return torch.tensor(encoded)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        # Extract image from bytes
        image = extract_image(row['image'])
        image = self.transform(image)

        # Get first caption
        captions = parse_captions(row['captions'])
        caption = captions[0]
        caption_encoded = self.encode_caption(caption)

        return image, caption_encoded

# Create dataset
train_dataset = RSICDDataset(train_df, vocab, transform)
valid_dataset = RSICDDataset(valid_df, vocab, transform)

print(f"✓ Datasets created:")
print(f"  Train dataset: {len(train_dataset)} samples")
print(f"  Valid dataset: {len(valid_dataset)} samples")

# Test __getitem__
print("\n✓ Testing dataset indexing...")
sample_image, sample_caption = train_dataset[0]
print(f"  Image tensor shape: {sample_image.shape}")
print(f"  Caption tensor shape: {sample_caption.shape}")
print(f"  Caption length: {len(sample_caption)}")
print(f"  Caption (encoded): {sample_caption.tolist()}")

# Decode caption
decoded_caption = [inv_vocab[idx.item()] for idx in sample_caption]
print(f"  Caption (decoded): {' '.join(decoded_caption)}")

# Test multiple samples
print("\n✓ Testing 5 random samples...")
import random
for i in random.sample(range(len(train_dataset)), 5):
    img, cap = train_dataset[i]
    print(f"  Sample {i}: image {img.shape}, caption length {len(cap)}")

print("\n✓ Dataset test passed!")

"""** Testing DataLoader**"""

print("\n" + "="*50)
print("PART 7: Testing DataLoader")
print("="*50)

def collate_fn(batch):
    """Custom collate function - just return the batch as-is"""
    return batch

# Create dataloaders
train_loader = DataLoader(
    train_dataset,
    batch_size=16,
    shuffle=True,
    collate_fn=collate_fn
)

valid_loader = DataLoader(
    valid_dataset,
    batch_size=16,
    shuffle=False,
    collate_fn=collate_fn
)

print(f"✓ DataLoaders created:")
print(f"  Train batches: {len(train_loader)}")
print(f"  Valid batches: {len(valid_loader)}")
print(f"  Batch size: 16")

# Test getting a batch
print("\n✓ Testing batch retrieval...")
batch = next(iter(train_loader))
print(f"  Batch type: {type(batch)}")
print(f"  Batch length: {len(batch)}")

images, captions = zip(*batch)
print(f"  Images in batch: {len(images)}")
print(f"  Captions in batch: {len(captions)}")

# Test stacking and padding
images_stacked = torch.stack(images)
captions_padded = nn.utils.rnn.pad_sequence(captions, batch_first=True, padding_value=0)

print(f"\n✓ After processing:")
print(f"  Stacked images shape: {images_stacked.shape}")
print(f"  Padded captions shape: {captions_padded.shape}")
print(f"  Caption lengths: {[len(c) for c in captions]}")

print("\n✓ DataLoader test passed!")

"""**PART 8: Test Model Architecture**"""

print("\n" + "="*50)
print("PART 8: Testing Model Architecture")
print("="*50)

# 8.1 Encodeur (ResNet50)
class EncoderCNN(nn.Module):
    def __init__(self, embed_size):
        super().__init__()
        resnet = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
        for param in resnet.parameters():
            param.requires_grad = False
        self.resnet = nn.Sequential(*list(resnet.children())[:-1])
        self.fc = nn.Linear(2048, embed_size)

    def forward(self, images):
        features = self.resnet(images).squeeze()
        if features.dim() == 1:  # Handle single image
            features = features.unsqueeze(0)
        features = self.fc(features)
        return features

# 8.2 Décodeur (LSTM)
class DecoderRNN(nn.Module):
    def __init__(self, embed_size, hidden_size, vocab_size):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, embed_size)
        self.lstm = nn.LSTM(embed_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, features, captions):
        embeddings = self.embed(captions)
        embeddings = torch.cat((features.unsqueeze(1), embeddings), 1)
        outputs, _ = self.lstm(embeddings)
        outputs = self.fc(outputs)
        return outputs

# 8.3 Initialize models
embed_size = 256
hidden_size = 512

print("✓ Creating models...")
encoder = EncoderCNN(embed_size).to(device)
decoder = DecoderRNN(embed_size, hidden_size, vocab_size).to(device)

print(f"\n✓ Encoder:")
print(f"  Embed size: {embed_size}")
trainable_params = sum(p.numel() for p in encoder.parameters() if p.requires_grad)
total_params = sum(p.numel() for p in encoder.parameters())
print(f"  Trainable parameters: {trainable_params:,}")
print(f"  Total parameters: {total_params:,}")

print(f"\n✓ Decoder:")
print(f"  Hidden size: {hidden_size}")
print(f"  Vocab size: {vocab_size}")
decoder_params = sum(p.numel() for p in decoder.parameters())
print(f"  Parameters: {decoder_params:,}")

# Test forward pass with one image
print("\n✓ Testing forward pass...")
test_batch = next(iter(train_loader))
images, captions = zip(*test_batch)
images = torch.stack(images).to(device)
captions = nn.utils.rnn.pad_sequence(captions, batch_first=True, padding_value=0).to(device)

print(f"  Input images shape: {images.shape}")
print(f"  Input captions shape: {captions.shape}")

# Encoder forward
features = encoder(images)
print(f"  Encoded features shape: {features.shape}")

# Decoder forward
outputs = decoder(features, captions[:, :-1])
print(f"  Decoder outputs shape: {outputs.shape}")
print(f"  Expected: [batch_size, max_caption_length, vocab_size]")

print("\n✓ Model architecture test passed!")

"""**PART 9: Test Loss & Optimizer**"""

print("\n" + "="*50)
print("PART 9: Testing Loss & Optimizer")
print("="*50)

# Define loss and optimizer
criterion = nn.CrossEntropyLoss(ignore_index=0)
params = list(decoder.parameters()) + list(encoder.fc.parameters())
optimizer = torch.optim.Adam(params, lr=1e-3)

print("✓ Loss function: CrossEntropyLoss (ignoring <PAD> token)")
print(f"✓ Optimizer: Adam")
print(f"  Learning rate: 1e-3")
print(f"  Optimizing parameters: {sum(p.numel() for p in params):,}")

# Test loss calculation
print("\n✓ Testing loss calculation...")
loss = criterion(
    outputs.reshape(-1, vocab_size),
    captions.reshape(-1)
)
print(f"  Loss value: {loss.item():.4f}")
print(f"  Loss is finite: {torch.isfinite(loss).item()}")

# Test backward pass
print("\n✓ Testing backward pass...")
optimizer.zero_grad()
loss.backward()
print("  Backward pass successful")

# Check gradients
has_grads = sum(1 for p in params if p.grad is not None)
print(f"  Parameters with gradients: {has_grads}/{len(params)}")

# Test optimizer step
print("\n✓ Testing optimizer step...")
optimizer.step()
print("  Optimizer step successful")

print("\n✓ Loss & Optimizer test passed!")

"""**PART 10: Test One Training Iteration**"""

print("\n" + "="*50)
print("PART 10: Testing One Training Iteration")
print("="*50)

encoder.train()
decoder.train()

print("✓ Models in training mode")

# Get one batch
batch = next(iter(train_loader))
images, captions = zip(*batch)
images = torch.stack(images).to(device)
captions = nn.utils.rnn.pad_sequence(captions, batch_first=True, padding_value=0).to(device)

print(f"✓ Batch loaded: {len(batch)} samples")

# Forward pass
print("\n✓ Running forward pass...")
features = encoder(images)
outputs = decoder(features, captions[:, :-1])

# Calculate loss
loss = criterion(
    outputs.reshape(-1, vocab_size),
    captions.reshape(-1)
)
print(f"  Loss: {loss.item():.4f}")

# Backward pass
print("\n✓ Running backward pass...")
optimizer.zero_grad()
loss.backward()
optimizer.step()
print("  Gradients computed and weights updated")

print("\n✓ Training iteration test passed!")
print("\n" + "="*50)
print("ALL TESTS PASSED! Ready for full training 🎉")
print("="*50)

"""**FULL TRAINING CODE**"""

print("\n" + "="*50)
print("BUILDING IMPROVED MODEL")
print("="*50)

# ===================================================================
# 1. IMPROVED DECODER WITH DROPOUT
# ===================================================================
class DecoderRNN_Improved(nn.Module):
    def __init__(self, embed_size, hidden_size, vocab_size, num_layers=2, dropout=0.5):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, embed_size)
        self.dropout = nn.Dropout(dropout)
        self.lstm = nn.LSTM(
            embed_size,
            hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0
        )
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, features, captions):
        embeddings = self.embed(captions)
        embeddings = self.dropout(embeddings)
        embeddings = torch.cat((features.unsqueeze(1), embeddings), 1)
        outputs, _ = self.lstm(embeddings)
        outputs = self.dropout(outputs)
        outputs = self.fc(outputs)
        return outputs

# ===================================================================
# 2. DATA AUGMENTATION TRANSFORMS
# ===================================================================
transform_train = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.RandomCrop((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

transform_val = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# ===================================================================
# 3. AUGMENTED DATASET WITH RANDOM CAPTION SELECTION
# ===================================================================
class RSICDDatasetAugmented(Dataset):
    def __init__(self, df, vocab, transform, use_random_caption=False):
        self.df = df
        self.vocab = vocab
        self.transform = transform
        self.use_random_caption = use_random_caption

    def __len__(self):
        return len(self.df)

    def encode_caption(self, caption):
        tokens = word_tokenize(caption.lower())
        encoded = [self.vocab["<START>"]]
        for token in tokens:
            encoded.append(self.vocab.get(token, self.vocab["<UNK>"]))
        encoded.append(self.vocab["<END>"])
        return torch.tensor(encoded)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        image = extract_image(row['image'])
        image = self.transform(image)

        captions = parse_captions(row['captions'])
        if self.use_random_caption and len(captions) > 1:
            import random
            caption = random.choice(captions)
        else:
            caption = captions[0]

        caption_encoded = self.encode_caption(caption)
        return image, caption_encoded

# ===================================================================
# 4. CREATE IMPROVED DATASETS AND DATALOADERS
# ===================================================================
train_dataset_improved = RSICDDatasetAugmented(train_df, vocab, transform_train, use_random_caption=True)
valid_dataset_improved = RSICDDatasetAugmented(valid_df, vocab, transform_val, use_random_caption=False)

train_loader_improved = DataLoader(train_dataset_improved, batch_size=32, shuffle=True, collate_fn=collate_fn)
valid_loader_improved = DataLoader(valid_dataset_improved, batch_size=32, shuffle=False, collate_fn=collate_fn)

print(f"✓ Augmented datasets created")
print(f"  Train: {len(train_dataset_improved)} samples")
print(f"  Valid: {len(valid_dataset_improved)} samples")

# ===================================================================
# 5. INITIALIZE IMPROVED MODEL
# ===================================================================
decoder_improved = DecoderRNN_Improved(
    embed_size=256,
    hidden_size=512,
    vocab_size=vocab_size,
    num_layers=2,
    dropout=0.5
).to(device)

print(f"\n✓ Improved decoder created")
print(f"  Layers: 2")
print(f"  Dropout: 0.5")
print(f"  Parameters: {sum(p.numel() for p in decoder_improved.parameters()):,}")

# ===================================================================
# 6. SETUP OPTIMIZER AND SCHEDULER
# ===================================================================
from torch.optim.lr_scheduler import ReduceLROnPlateau

params_improved = list(decoder_improved.parameters()) + list(encoder.fc.parameters())
optimizer_improved = torch.optim.Adam(params_improved, lr=1e-3)
scheduler = ReduceLROnPlateau(optimizer_improved, mode='min', factor=0.5, patience=2)
print(f"\n✓ Optimizer setup")
print(f"  Learning rate: 1e-3")
print(f"  Scheduler: ReduceLROnPlateau")

# ===================================================================
# 7. EARLY STOPPING CLASS
# ===================================================================
class EarlyStopping:
    def __init__(self, patience=3, min_delta=0.001):
        self.patience = patience
        self.min_delta = min_delta
        self.counter = 0
        self.best_loss = None
        self.early_stop = False

    def __call__(self, val_loss):
        if self.best_loss is None:
            self.best_loss = val_loss
        elif val_loss > self.best_loss - self.min_delta:
            self.counter += 1
            print(f"    Early stopping counter: {self.counter}/{self.patience}")
            if self.counter >= self.patience:
                self.early_stop = True
        else:
            self.best_loss = val_loss
            self.counter = 0

early_stopping = EarlyStopping(patience=3)
print(f"\n✓ Early stopping initialized (patience=3)")

# ===================================================================
# 8. IMPROVED TRAINING LOOP
# ===================================================================
print("\n" + "="*50)
print("STARTING IMPROVED TRAINING")
print("="*50)

num_epochs = 10
best_val_loss = float('inf')

# Training history
history_improved = {
    'train_loss': [],
    'val_loss': [],
    'learning_rate': []
}

for epoch in range(num_epochs):
    print(f"\n{'='*50}")
    print(f"EPOCH {epoch+1}/{num_epochs}")
    print(f"{'='*50}")

    # ==================== TRAINING ====================
    encoder.train()
    decoder_improved.train()
    total_train_loss = 0
    batch_count = 0

    for batch_idx, batch in enumerate(train_loader_improved):
        # Prepare batch
        images, captions = zip(*batch)
        images = torch.stack(images).to(device)
        captions = nn.utils.rnn.pad_sequence(
            captions, batch_first=True, padding_value=0
        ).to(device)

        # Forward pass
        features = encoder(images)
        outputs = decoder_improved(features, captions[:, :-1])

        # Calculate loss
        loss = criterion(
            outputs.reshape(-1, vocab_size),
            captions.reshape(-1)
        )

        # Backward pass
        optimizer_improved.zero_grad()
        loss.backward()

        # Gradient clipping
        torch.nn.utils.clip_grad_norm_(params_improved, max_norm=5.0)

        optimizer_improved.step()

        total_train_loss += loss.item()
        batch_count += 1

        # Print progress every 50 batches
        if (batch_idx + 1) % 50 == 0:
            avg_loss = total_train_loss / batch_count
            print(f"  Batch [{batch_idx+1}/{len(train_loader_improved)}] - Loss: {loss.item():.4f} - Avg: {avg_loss:.4f}")

    avg_train_loss = total_train_loss / batch_count
    history_improved['train_loss'].append(avg_train_loss)

    # ==================== VALIDATION ====================
    encoder.eval()
    decoder_improved.eval()
    total_val_loss = 0
    val_batch_count = 0

    print(f"\n  Validating...")
    with torch.no_grad():
        for batch in valid_loader_improved:
            images, captions = zip(*batch)
            images = torch.stack(images).to(device)
            captions = nn.utils.rnn.pad_sequence(
                captions, batch_first=True, padding_value=0
            ).to(device)

            features = encoder(images)
            outputs = decoder_improved(features, captions[:, :-1])

            loss = criterion(
                outputs.reshape(-1, vocab_size),
                captions.reshape(-1)
            )

            total_val_loss += loss.item()
            val_batch_count += 1

    avg_val_loss = total_val_loss / val_batch_count
    history_improved['val_loss'].append(avg_val_loss)

    # Update learning rate
    current_lr = optimizer_improved.param_groups[0]['lr']
    history_improved['learning_rate'].append(current_lr)
    scheduler.step(avg_val_loss)

    # Print epoch summary
    print(f"\n  EPOCH {epoch+1} SUMMARY:")
    print(f"    Train Loss: {avg_train_loss:.4f}")
    print(f"    Val Loss:   {avg_val_loss:.4f}")
    print(f"    Learning Rate: {current_lr:.6f}")

    # Save best model
    if avg_val_loss < best_val_loss:
        best_val_loss = avg_val_loss
        torch.save({
            'epoch': epoch,
            'encoder_state_dict': encoder.state_dict(),
            'decoder_state_dict': decoder_improved.state_dict(),
            'optimizer_state_dict': optimizer_improved.state_dict(),
            'val_loss': avg_val_loss,
        }, 'best_model_improved.pth')
        print(f"    ✓ Best model saved! (Val Loss: {avg_val_loss:.4f})")

    # Early stopping check
    early_stopping(avg_val_loss)
    if early_stopping.early_stop:
        print(f"\n  ⚠️ Early stopping triggered at epoch {epoch+1}")
        break

print("\n" + "="*50)
print("IMPROVED TRAINING COMPLETED!")
print("="*50)

# ===================================================================
# 9. PLOT COMPARISON
# ===================================================================
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# Loss comparison
axes[0].plot(history['train_loss'], label='Baseline Train', marker='o', linestyle='--', alpha=0.7)
axes[0].plot(history['val_loss'], label='Baseline Val', marker='s', linestyle='--', alpha=0.7)
axes[0].plot(history_improved['train_loss'], label='Improved Train', marker='o', linewidth=2)
axes[0].plot(history_improved['val_loss'], label='Improved Val', marker='s', linewidth=2)
axes[0].set_xlabel('Epoch', fontsize=12)
axes[0].set_ylabel('Loss', fontsize=12)
axes[0].set_title('Loss Comparison: Baseline vs Improved', fontsize=14)
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Learning rate schedule
axes[1].plot(history_improved['learning_rate'], marker='o', color='green', linewidth=2)
axes[1].set_xlabel('Epoch', fontsize=12)
axes[1].set_ylabel('Learning Rate', fontsize=12)
axes[1].set_title('Learning Rate Schedule', fontsize=14)
axes[1].grid(True, alpha=0.3)
axes[1].set_yscale('log')

plt.tight_layout()
plt.show()

print(f"\n📊 Final Results Comparison:")
print(f"{'='*50}")
print(f"Baseline Model:")
print(f"  Best Val Loss: {min(history['val_loss']):.4f}")
print(f"  Final Train Loss: {history['train_loss'][-1]:.4f}")
print(f"  Overfitting Gap: {min(history['val_loss']) - history['train_loss'][-1]:.4f}")
print(f"\nImproved Model:")
print(f"  Best Val Loss: {best_val_loss:.4f}")
print(f"  Final Train Loss: {history_improved['train_loss'][-1]:.4f}")
print(f"  Overfitting Gap: {best_val_loss - history_improved['train_loss'][-1]:.4f}")
print(f"\nImprovement:")
print(f"  Val Loss Reduction: {min(history['val_loss']) - best_val_loss:.4f}")
print(f"  Overfitting Reduction: {(min(history['val_loss']) - history['train_loss'][-1]) - (best_val_loss - history_improved['train_loss'][-1]):.4f}")
print(f"{'='*50}")

"""**INFERENCE & TESTING**"""

# Define the model directory path
import os
model_dir = '/content/drive/MyDrive/image_captioning_models'

# Verify the file exists
if os.path.exists(os.path.join(model_dir, 'best_model_improved.pth')):
    print(f"✓ Model found at: {model_dir}")
else:
    print("❌ Model not found. Checking alternative locations...")
    # Check current directory
    if os.path.exists('best_model_improved.pth'):
        model_dir = '.'
        print(f"✓ Found model in current directory")

print("\n" + "="*50)
print("TESTING IMPROVED MODEL")
print("="*50)

# Load best model
checkpoint = torch.load(os.path.join(model_dir, 'best_model_improved.pth'))
encoder.load_state_dict(checkpoint['encoder_state_dict'])
decoder_improved.load_state_dict(checkpoint['decoder_state_dict'])
print(f"✓ Loaded best model from epoch {checkpoint['epoch']}")
print(f"✓ Validation Loss: {checkpoint['val_loss']:.4f}")

# Generation functions
def generate_caption_greedy(image, encoder, decoder, max_len=20):
    encoder.eval()
    decoder.eval()
    with torch.no_grad():
        feature = encoder(image.unsqueeze(0).to(device))
        word = torch.tensor([[vocab["<START>"]]]).to(device)
        caption = []
        for _ in range(max_len):
            output = decoder(feature, word)
            pred = output.argmax(2)[:, -1].item()
            if pred == vocab["<END>"]:
                break
            caption.append(inv_vocab.get(pred, "<UNK>"))
            word = torch.cat([word, torch.tensor([[pred]]).to(device)], 1)
    return " ".join(caption)

def generate_caption_beam_search(image, encoder, decoder, beam_width=5, max_len=20):
    encoder.eval()
    decoder.eval()
    with torch.no_grad():
        feature = encoder(image.unsqueeze(0).to(device))
        beams = [([vocab["<START>"]], 0.0)]
        for _ in range(max_len):
            new_beams = []
            for seq, score in beams:
                if seq[-1] == vocab["<END>"]:
                    new_beams.append((seq, score))
                    continue
                word = torch.tensor([seq]).to(device)
                output = decoder(feature, word)
                log_probs = torch.log_softmax(output[0, -1], dim=0)
                top_k_probs, top_k_indices = torch.topk(log_probs, beam_width)
                for prob, idx in zip(top_k_probs, top_k_indices):
                    new_seq = seq + [idx.item()]
                    new_score = score + prob.item()
                    new_beams.append((new_seq, new_score))
            beams = sorted(new_beams, key=lambda x: x[1], reverse=True)[:beam_width]
            if all(seq[-1] == vocab["<END>"] for seq, _ in beams):
                break
        best_seq = beams[0][0]
        caption = [inv_vocab.get(idx, "<UNK>") for idx in best_seq
                   if idx not in [vocab["<START>"], vocab["<END>"]]]
    return " ".join(caption)

# Test on samples
print("\n" + "="*50)
print("GENERATING CAPTIONS")
print("="*50)

test_indices = [10, 50, 100, 200, 300]

for i, idx in enumerate(test_indices):
    image, _ = valid_dataset_improved[idx]

    # Generate captions
    greedy = generate_caption_greedy(image, encoder, decoder_improved)
    beam = generate_caption_beam_search(image, encoder, decoder_improved, beam_width=5)

    # Get real caption
    real_captions = parse_captions(valid_df.iloc[idx]['captions'])

    print(f"\n{'='*60}")
    print(f"Sample {i+1} (Index {idx}):")
    print(f"  Greedy:      {greedy}")
    print(f"  Beam Search: {beam}")
    print(f"  Real:        {real_captions[0][:80]}...")

# Visualize
num_samples = 5
fig, axes = plt.subplots(2, num_samples, figsize=(20, 8))

for i, idx in enumerate(test_indices):
    image, _ = valid_dataset_improved[idx]

    greedy = generate_caption_greedy(image, encoder, decoder_improved)
    beam = generate_caption_beam_search(image, encoder, decoder_improved, beam_width=5)

    # Denormalize
    denorm = image.permute(1, 2, 0).cpu().numpy()
    denorm = denorm * [0.229, 0.224, 0.225] + [0.485, 0.456, 0.406]
    denorm = denorm.clip(0, 1)

    # Top: Greedy
    axes[0, i].imshow(denorm)
    axes[0, i].axis('off')
    axes[0, i].set_title(f"Greedy:\n{greedy[:50]}...", fontsize=8)

    # Bottom: Beam
    axes[1, i].imshow(denorm)
    axes[1, i].axis('off')
    axes[1, i].set_title(f"Beam:\n{beam[:50]}...", fontsize=8)

axes[0, 0].set_ylabel('Greedy', fontsize=12, rotation=0, labelpad=40)
axes[1, 0].set_ylabel('Beam', fontsize=12, rotation=0, labelpad=40)

plt.tight_layout()
plt.show()

print("\n✅ TESTING COMPLETE!")
print(f"\nModel Performance:")
print(f"  Best Val Loss: {checkpoint['val_loss']:.4f}")
print(f"  Saved at: {model_dir}")

"""**Visualize samples with images**"""

# Define the generation function
def generate_caption(image, encoder, decoder, max_len=20):
    encoder.eval()
    decoder.eval()
    with torch.no_grad():
        feature = encoder(image.unsqueeze(0).to(device))
        word = torch.tensor([[vocab["<START>"]]]).to(device)
        caption = []
        for _ in range(max_len):
            output = decoder(feature, word)
            pred = output.argmax(2)[:, -1].item()
            if pred == vocab["<END>"]:
                break
            caption.append(inv_vocab.get(pred, "<UNK>"))
            word = torch.cat([word, torch.tensor([[pred]]).to(device)], 1)
    return " ".join(caption)

# NOW visualize
num_samples = 5
test_indices = [10, 50, 100, 200, 300]

fig, axes = plt.subplots(1, num_samples, figsize=(25, 5))

for i, idx in enumerate(test_indices):
    image, _ = valid_dataset_improved[idx]

    # Generate caption
    generated = generate_caption(image, encoder, decoder_improved)

    # Denormalize image
    denorm = image.permute(1, 2, 0).cpu().numpy()
    denorm = denorm * [0.229, 0.224, 0.225] + [0.485, 0.456, 0.406]
    denorm = denorm.clip(0, 1)

    # Display
    axes[i].imshow(denorm)
    axes[i].axis('off')
    axes[i].set_title(f"Generated:\n{generated[:60]}...", fontsize=9)

plt.tight_layout()
plt.show()

# Print captions
print("\n" + "="*60)
print("GENERATED CAPTIONS")
print("="*60)

for i, idx in enumerate(test_indices):
    image, _ = valid_dataset_improved[idx]
    generated = generate_caption(image, encoder, decoder_improved)
    real_captions = parse_captions(valid_df.iloc[idx]['captions'])

    print(f"\nSample {i+1}:")
    print(f"  Generated: {generated}")
    print(f"  Real:      {real_captions[0][:80]}...")